### ISSUE TITLE
Port to python 3

### ISSUE THREAD

**Issue by micwoj92** [pflouret/ccx2#1]

**Comment by hartwork** [comment]
Yes please

**Comment by hartwork** [comment]
@pflouret hypothetically, if I tried a port to Python 3.7+ in a pull request, would that have a chance to be reviewed and merged and released to PyPI?

**Comment by pflouret** [comment]
@hartwork Sounds like it'd be a lot of work, but sure!

**Comment by hartwork** [comment]
@pflouret alright, let's see how far I can get…

**Comment by hartwork** [comment]
@pflouret please check pull request #2. I'm looking forward to your and @micwoj92's feedback.
